const startTenHands = async () => {
  try {
    console.log("starting");
  } catch (error) {
    console.log("Error");
  }
};

startTenHands();
